services:
  - type: web
    name: tramoo-backend
    env: node
    buildCommand: |
      cd src/backend
      npm install --production=false
    startCommand: node server.js
    envVars:
      - key: NODE_VERSION
        value: 18.x
      - key: MONGODB_URI
        fromDatabase:
          name: mongodb
          property: connectionString
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        generateValue: true
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: GOOGLE_REDIRECT_URI
        sync: false
      - key: VITE_FRONTEND_URL
        sync: false
    plan: free
